runtime: python39  # Use Python 3.9 or your preferred version

instance_class: F2  # Adjust instance class based on your application's needs

entrypoint: web: streamlit run CRUD.py --server.port $PORT

# Environment variables for connecting to your localhost MySQL database
env_variables:
  MYSQL_HOST: 'localhost'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'Princessfranz02'
  MYSQL_DATABASE: 'dbCandletonia'
  MYSQL_PORT: '3306'  # Adjust port if necessary, default is 3306

# Automatic scaling settings (adjust based on your expected traffic)
automatic_scaling:
  min_instances: 1
  max_instances: 5  # Adjust based on your scalability needs
  target_cpu_utilization: 0.65  # Adjust based on your application's CPU usage

# If using Streamlit, specify the command to run your application
handlers:
  - url: .*
    script: auto

# Health check endpoint configuration
readiness_check:
  path: "/healthcheck"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2