runtime: python39
env: flex

instance_class: F2

# Environment variables for connecting to your localhost MySQL database
env_variables:
  MYSQL_HOST: 'localhost'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'Princessfranz02'
  MYSQL_DATABASE: 'dbCandletonia'
  MYSQL_PORT: '3306'

# Specify the entrypoint command to run your Streamlit application
entrypoint: streamlit run CRUD.py --server.port $PORT

# Health check endpoint configuration
readiness_check:
  path: "/healthcheck"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2